---
- name: Deploy Online Boutique with existing Kubernetes manifests
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    manifests_path: "../../microservices-demo/kubernetes-manifests"
    namespace: default
    
  tasks:
    - name: Ensure namespace exists
      shell: kubectl create namespace {{ namespace }} --dry-run=client -o yaml | kubectl apply -f -
      ignore_errors: true
      
    - name: Find all Kubernetes manifest files
      find:
        paths: "{{ manifests_path }}"
        patterns: "*.yaml"
        file_type: file
      register: manifest_files
      
    - name: Display found manifest files
      debug:
        msg: "Found {{ manifest_files.files | length }} manifest files"
        
    - name: Apply each Kubernetes manifest
      shell: kubectl apply -f "{{ item.path }}" -n {{ namespace }}
      loop: "{{ manifest_files.files }}"
      when: item.path is not search('kustomization.yaml')
      register: apply_results
      
    - name: Display apply results
      debug:
        msg: "Applied manifest: {{ item.item.path }} - {{ item.stdout }}"
      loop: "{{ apply_results.results }}"
      when: item.stdout is defined
      
    - name: Wait for all deployments to be ready
      shell: kubectl wait --for=condition=available --timeout=300s deployment --all -n {{ namespace }}
      register: wait_result
      ignore_errors: true
      
    - name: Show deployment status
      shell: kubectl get deployments,services,pods -n {{ namespace }}
      register: status_output
      
    - name: Display final status
      debug:
        msg: "{{ status_output.stdout_lines }}"
