---
- name: "Deploy {{ service_config.service_name }} microservice"
  block:
    - name: "Generate Kubernetes manifest for {{ service_config.service_name }}"
      template:
        src: ../templates/microservice-deployment.yml.j2
        dest: "/tmp/{{ service_config.service_name }}-deployment.yml"
      vars:
        service_name: "{{ service_config.service_name }}"
        namespace: "{{ service_config.namespace | default(namespace) }}"
        replicas: "{{ service_config.replicas | default(1) }}"
        port: "{{ service_config.port | default(8080) }}"
        image_registry: "{{ image_registry }}"
        version: "{{ version }}"
        
    - name: "Apply {{ service_config.service_name }} deployment"
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/tmp/' + service_config.service_name + '-deployment.yml') | from_yaml_all }}"
        
    - name: "Clean up temporary manifest for {{ service_config.service_name }}"
      file:
        path: "/tmp/{{ service_config.service_name }}-deployment.yml"
        state: absent
        
  rescue:
    - name: "Handle deployment failure for {{ service_config.service_name }}"
      debug:
        msg: "Failed to deploy {{ service_config.service_name }}: {{ ansible_failed_result.msg }}"
        
    - name: "Rollback {{ service_config.service_name }} if needed"
      kubernetes.core.k8s:
        state: absent
        api_version: apps/v1
        kind: Deployment
        name: "{{ service_config.service_name }}"
        namespace: "{{ service_config.namespace | default(namespace) }}"
      ignore_errors: true
