---
- name: Deploy Individual Microservice
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    namespace: default
    image_registry: "gcr.io/google-samples/microservices-demo"
    version: "latest"
    service_name: "{{ target_service | default('frontend') }}"
    
  tasks:
    - name: Validate service name
      fail:
        msg: "Service {{ service_name }} not found in inventory"
      when: service_name not in groups['microservices']
      
    - name: Ensure namespace exists
      kubernetes.core.k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: Namespace
        state: present
        
    - name: Deploy target microservice
      include_tasks: tasks/deploy-microservice.yml
      vars:
        service_config: "{{ hostvars[service_name] }}"
        
    - name: Wait for deployment to be ready
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: "{{ service_name }}"
        namespace: "{{ namespace }}"
        wait: true
        wait_condition:
          type: Available
          status: "True"
        wait_timeout: 300
        
    - name: Display service status
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Service
        name: "{{ service_name }}"
        namespace: "{{ namespace }}"
      register: service_info
      
    - name: Show deployment result
      debug:
        msg: 
          - "Service {{ service_name }} deployed successfully!"
          - "Service IP: {{ service_info.resources[0].spec.clusterIP }}"
          - "Service Port: {{ service_info.resources[0].spec.ports[0].port }}"
